services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - media_volume:/app/solution_site/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - web-net

  web:
    build: .
    volumes:
      - media_volume:/app/solution_site/media
      - sqlite_data:/app/solution_site/db
    # environment:
    #   - DEBUG=True
    #   - ALLOWED_HOSTS=*
    #   - DJANGO_SUPERUSER_USERNAME=admin
    #   - DJANGO_SUPERUSER_EMAIL=email@gmail.com
    #   - DJANGO_SUPERUSER_PASSWORD=securepassword123
    networks:
      - web-net
    ports:
      - 8000:8000

      
volumes:
  media_volume:
  sqlite_data:


networks:
  web-net:
    driver: bridge