services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - media_volume:/app/solution_site/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    build: .
    volumes:
      - media_volume:/app/solution_site/media
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=email@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=securepassword123
    expose:
      - "8000"
      
volumes:
  media_volume: