version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    build: .
    volumes:
      - sqlite_data:/app/solution_site/db.sqlite3
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1
    expose:
      - "8000"
    # Убираем command, так как используем ENTRYPOINT

volumes:
  sqlite_data: