# Generated by Django 4.2.23 on 2025-07-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quotes/'),
        ),
    ]
